version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
  blog:
    image: 'bitnami/ghost:latest'
    expose:
      - '2368'
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=your.email@example.com