version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - HOSTNAME=mariadb
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - /var/docker/ghost/mariadb-persistence:/bitnami
    networks:
      - nginx_web
  blog:
    image: 'bitnami/ghost:latest'
    expose:
      - '2368'
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=your.email@example.com
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_PASSWORD=
      - GHOST_DATABASE_NAME=bitnami_ghost
    volumes:
      - /var/docker/ghost/ghost-persistence:/bitnami
    networks:
      - nginx_web

networks:
  nginx_web:
    external: true